# Generated by Django 5.0.7 on 2024-07-17 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academics', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='Users.teacher'),
        ),
        migrations.AddField(
            model_name='coursedepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Academics.department'),
        ),
        migrations.AddField(
            model_name='sectioncourseoffering',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_course_offerings', to='Academics.courseoffering'),
        ),
        migrations.AddField(
            model_name='sectioncourseoffering',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_course_offerings', to='Academics.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='course_offerings',
            field=models.ManyToManyField(related_name='sections', through='Academics.SectionCourseOffering', to='Academics.courseoffering'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section_course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Academics.sectioncourseoffering'),
        ),
        migrations.AddField(
            model_name='studentacademicrecord',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='Academics.academicperiod'),
        ),
        migrations.AddField(
            model_name='studentacademicrecord',
            name='academic_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='Academics.academicstatus'),
        ),
        migrations.AddField(
            model_name='studentacademicrecord',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='Academics.department'),
        ),
        migrations.AddField(
            model_name='studentacademicrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='Users.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Academics.studentacademicrecord'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='section_course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='Academics.sectioncourseoffering'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Users.teacher'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['course_department', 'academic_period'], name='Academics_c_course__fc25e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course_department', 'academic_period', 'semester_number')},
        ),
        migrations.AddIndex(
            model_name='coursedepartment',
            index=models.Index(fields=['course', 'department'], name='Academics_c_course__4a1394_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursedepartment',
            unique_together={('course', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='sectioncourseoffering',
            unique_together={('section', 'course_offering')},
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['section_name'], name='Academics_s_section_fcebe9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentacademicrecord',
            index=models.Index(fields=['student', 'academic_period'], name='Academics_s_student_26b74c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentacademicrecord',
            index=models.Index(fields=['department', 'academic_period'], name='Academics_s_departm_894644_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentacademicrecord',
            unique_together={('student', 'department', 'academic_period')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student_record', 'section_course_offering'], name='Academics_e_student_6fc2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['registration_date'], name='Academics_e_registr_c89657_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student_record', 'section_course_offering')},
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['teacher', 'section_course_offering'], name='Academics_t_teacher_1c143b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'section_course_offering')},
        ),
    ]
